---
new_page_extension: md
auto_deploy: true
admin_path: ''
webhook_url: 
sections:
- type: heading
  label: Component Documentation
- type: directory
  path: content/Components
  label: Components
  create: documents
  match: "**/*"
  templates:
  - component
- type: directory
  path: content/Web_Components
  label: Web components
  create: documents
  match: "**/*"
  templates:
  - web-component
- type: heading
  label: Design & Development Docs
- type: directory
  path: content/Design
  label: Design
  create: documents
  match: "**/*"
  templates:
  - design
- type: directory
  path: content/Develop
  label: Develop
  create: all
  match: "**/*"
- type: heading
  label: Home & About Pages
- type: directory
  path: content/About
  label: About
  create: all
  match: "**/*"
- type: directory
  path: content
  label: Pages
  create: all
  match: "*"
upload_dir: static/images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_command: hugo -E -F -D -b $DEPLOY_URL -d public
  publish_command: hugo -d public
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.53
  publish_env:
  - HUGO_ENV=production
  - HUGO_VERSION=0.53
  preview_output_directory: public
  output_directory: public
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
version: '0.53'
